### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by TroySchmidt** [connorshea/vscode-test-explorer-status-bar#5]
Unable to install because, the extension 'connorshea.vscode-test-explorer-status-bar' compatible with current version '1.33.1' of VS Code is not found.

**Comment by AlexHaxe** [comment]
According to `package.json` status bar extension requires VSCode 1.34.0 or newer. I don't know if there was an API change in 1.34 that status bar extension relies on, but I guess that was the current version back when making an inital release of status bar extension.

You probably have your reasons to stay with 1.33.1, and it might just be that one line in `package.json` that keeps status bar extension from showing up for you. 
To test it you can put a git version into your extensions folder, change that requirement, compile and launch your VSCode to see if it works

**Comment by TroySchmidt** [comment]
I am using VSCodium and didn't realize in April they didn't have auto update.  So I was stuck on old version.  I updated and it installed without problems.  Thanks!
